kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-ui
  labels:
    k8s-app: web-ui
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      k8s-app: web-ui
  template:
    metadata:
      name: web-ui
      labels:
        k8s-app: web-ui
    spec:
      containers:
        - name: web-ui
          image: 'cr.yandex/crpudm53vvciv4b12jrt/test:latest'
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          env:
            - name: NODE_ENV
              value: test
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
